/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmyslRouteImport } from './routes/umysl'
import { Route as SpecialistsRouteImport } from './routes/specialists'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CialoRouteImport } from './routes/cialo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecjalisciSlugRouteImport } from './routes/specjalisci.$slug'
import { Route as SpecialistsSlugRouteImport } from './routes/specialists.$slug'

const UmyslRoute = UmyslRouteImport.update({
  id: '/umysl',
  path: '/umysl',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsRoute = SpecialistsRouteImport.update({
  id: '/specialists',
  path: '/specialists',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CialoRoute = CialoRouteImport.update({
  id: '/cialo',
  path: '/cialo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecjalisciSlugRoute = SpecjalisciSlugRouteImport.update({
  id: '/specjalisci/$slug',
  path: '/specjalisci/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsSlugRoute = SpecialistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpecialistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cialo': typeof CialoRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/specialists': typeof SpecialistsRouteWithChildren
  '/umysl': typeof UmyslRoute
  '/specialists/$slug': typeof SpecialistsSlugRoute
  '/specjalisci/$slug': typeof SpecjalisciSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cialo': typeof CialoRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/specialists': typeof SpecialistsRouteWithChildren
  '/umysl': typeof UmyslRoute
  '/specialists/$slug': typeof SpecialistsSlugRoute
  '/specjalisci/$slug': typeof SpecjalisciSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cialo': typeof CialoRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/specialists': typeof SpecialistsRouteWithChildren
  '/umysl': typeof UmyslRoute
  '/specialists/$slug': typeof SpecialistsSlugRoute
  '/specjalisci/$slug': typeof SpecjalisciSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cialo'
    | '/contact'
    | '/pricing'
    | '/specialists'
    | '/umysl'
    | '/specialists/$slug'
    | '/specjalisci/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cialo'
    | '/contact'
    | '/pricing'
    | '/specialists'
    | '/umysl'
    | '/specialists/$slug'
    | '/specjalisci/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cialo'
    | '/contact'
    | '/pricing'
    | '/specialists'
    | '/umysl'
    | '/specialists/$slug'
    | '/specjalisci/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CialoRoute: typeof CialoRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  SpecialistsRoute: typeof SpecialistsRouteWithChildren
  UmyslRoute: typeof UmyslRoute
  SpecjalisciSlugRoute: typeof SpecjalisciSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/umysl': {
      id: '/umysl'
      path: '/umysl'
      fullPath: '/umysl'
      preLoaderRoute: typeof UmyslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists': {
      id: '/specialists'
      path: '/specialists'
      fullPath: '/specialists'
      preLoaderRoute: typeof SpecialistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cialo': {
      id: '/cialo'
      path: '/cialo'
      fullPath: '/cialo'
      preLoaderRoute: typeof CialoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specjalisci/$slug': {
      id: '/specjalisci/$slug'
      path: '/specjalisci/$slug'
      fullPath: '/specjalisci/$slug'
      preLoaderRoute: typeof SpecjalisciSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/$slug': {
      id: '/specialists/$slug'
      path: '/$slug'
      fullPath: '/specialists/$slug'
      preLoaderRoute: typeof SpecialistsSlugRouteImport
      parentRoute: typeof SpecialistsRoute
    }
  }
}

interface SpecialistsRouteChildren {
  SpecialistsSlugRoute: typeof SpecialistsSlugRoute
}

const SpecialistsRouteChildren: SpecialistsRouteChildren = {
  SpecialistsSlugRoute: SpecialistsSlugRoute,
}

const SpecialistsRouteWithChildren = SpecialistsRoute._addFileChildren(
  SpecialistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CialoRoute: CialoRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  SpecialistsRoute: SpecialistsRouteWithChildren,
  UmyslRoute: UmyslRoute,
  SpecjalisciSlugRoute: SpecjalisciSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
